Objetivo 0: Resolución del juego de Rol
javigp2002/LazyFood pull request #1
Opened 2023-09-15 12:41 UTC by javigp2002

2023-09-17 23:15 UTC, javigp2002 commented
- [x] **¿Se trata de un problema real del que se tenga conocimiento personal?**
Como estudiante, elegir cada semana mi menú me supone un gasto de energía y tiempo innecesario. Por ello, una buena implementación de este podría llegar a ahorrarme una buena cantidad de tiempo de manera que yo solo cocine y compre.

- [x] **¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?**
El despliegue en la nube puede ser esencial para poder acceder a los datos desde cualquier dispositivo y de manera que se pueda consultar en distintos lugares.

- [x] **¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse solo almacenando y buscando?**
Conocer los gustos y preferencias del usuario es costoso para crear un modelo válido, es decir, conseguir que el usuario confie en el criterio de la aplicación.

- [x] **¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?**
El usuario tendrá que marcar una lista indicando brevemente sus régimen alimenticio (vegetariano, vegano...) o incluso distintos gustos. Por otro lado, conseguiremos los datos de estás recetas y los alimentos que llevan para ser listados de una Base de Datos.

-[x]**¿Se ha incluído la configuración del repositorio y se ha enlazado desde el 'README'?**
-[x]**¿Has seguido la lista de comprobación o estás marcando al buen tuntún todo?**

2023-09-17 23:18 UTC, javigp2002 commented
- [x] **¿Se trata de un problema real del que se tenga conocimiento personal?**
Como estudiante, elegir cada semana mi menú me supone un gasto de energía y tiempo innecesario. Por ello, una buena implementación de este podría llegar a ahorrarme una buena cantidad de tiempo de manera que yo solo cocine y compre.

- [x] **¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?**
El despliegue en la nube puede ser esencial para poder acceder a los datos desde cualquier dispositivo y de manera que se pueda consultar en distintos lugares.

- [x] **¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse solo almacenando y buscando?**
Conocer los gustos y preferencias del usuario es costoso para crear un modelo válido, es decir, conseguir que el usuario confie en el criterio de la aplicación.

- [x] **¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?**
    El usuario tendrá que marcar una lista indicando brevemente sus régimen alimenticio (vegetariano, vegano...) o incluso distintos gustos. Por otro lado, conseguiremos los datos de estás recetas y los alimentos que llevan para ser listados de una Base de Datos.

- [x] **¿Se ha incluído la configuración del repositorio y se ha enlazado desde el 'README'? **
- [x] **¿Has seguido la lista de comprobación o estás marcando al buen tuntún todo?**

2023-09-18 09:31 UTC, JJ commented
> * [x]  **¿Se trata de un problema real del que se tenga conocimiento personal?**
>       Como estudiante, elegir cada semana mi menú me supone un gasto de energía y tiempo innecesario. Por ello, una buena implementación de este podría llegar a ahorrarme una buena cantidad de tiempo de manera que yo solo cocine y compre.
> 
>     * [x]  **¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?**
>       El despliegue en la nube puede ser esencial para poder acceder a los datos desde cualquier dispositivo y de manera que se pueda consultar en distintos lugares.
> 
>     * [x]  **¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse solo almacenando y buscando?**
>       Conocer los gustos y preferencias del usuario es costoso para crear un modelo válido, es decir, conseguir que el usuario confie en el criterio de la aplicación.
> 
>     * [x]  **¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?**
>       El usuario tendrá que marcar una lista indicando brevemente sus régimen alimenticio (vegetariano, vegano...) o incluso distintos gustos. Por otro lado, conseguiremos los datos de estás recetas y los alimentos que llevan para ser listados de una Base de Datos.
> 
>     * [x]  **¿Se ha incluído la configuración del repositorio y se ha enlazado desde el 'README'?**
> 

Esto lo tienes que poner en el cuerpo del PR, en vez de dejarlo vacío.

>     * [x]  **¿Has seguido la lista de comprobación o estás marcando al buen tuntún todo?**

¿Has visto lo que has marcado aquí?

2023-09-18 09:33 UTC, JJ requested changes
Por favor, mira [los errores frecuents](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md). "El problema de" no es una descripción de un problema que se pueda usar para desarrollar un producto.

2023-09-18 16:10 UTC, JJ commented
> * [x]  **¿Se trata de un problema real del que se tenga conocimiento personal?**
>       Como estudiante, elegir cada semana mi menú me supone un gasto de energía y tiempo innecesario. Por ello, una buena implementación de este podría llegar a ahorrarme una buena cantidad de tiempo de manera que yo solo cocine y compre.
> 
>     * [x]  **¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?**
>       El despliegue en la nube puede ser esencial para poder acceder a los datos desde cualquier dispositivo y de manera que se pueda consultar en distintos lugares.
> 
>     * [x]  **¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse solo almacenando y buscando?**
>       Conocer los gustos y preferencias del usuario es costoso para crear un modelo válido, es decir, conseguir que el usuario confie en el criterio de la aplicación.
> 

De [las preguntas frecuentes descritas en el objetivo](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#tiene-que-haber-algún-negocio-para-que-pueda-llamarse-lógica-de-negocio): 

> En inglés se usa a veces business para indicar la parte importante de algo, o la que hace el trabajo. 

No tiene nada que ver con el "conocimiento" de ningún aspecto del problema o la "confianza" del usuario, sino con el procesamiento no trivial de datos para solucionar el problema del cliente.

También sería conveniente que cambiaras el título del PR siguiendo las instrucciones, y lo que realmente contiene (que ya no es un juego de rol)

2023-09-18 16:26 UTC, javigp2002 commented
@JJ Entiendo que le nueva explicación de la lógica de negocio se adecua mejor a la pregunta.

> > * [x]   **¿Se trata de un problema real del que se tenga conocimiento personal?**
> >   Como estudiante, elegir cada semana mi menú me supone un gasto de energía y tiempo innecesario. Por ello, una buena implementación de este podría llegar a ahorrarme una buena cantidad de tiempo de manera que yo solo cocine y compre.
> >   
> >   * [x]   **¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?**
> >     El despliegue en la nube puede ser esencial para poder acceder a los datos desde cualquier dispositivo y de manera que se pueda consultar en distintos lugares.
> >   * [x]   **¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse solo almacenando y buscando?**
> >     Conocer los gustos y preferencias del usuario es costoso para crear un modelo válido, es decir, conseguir que el usuario confie en el criterio de la aplicación.
> 
> De [las preguntas frecuentes descritas en el objetivo](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#tiene-que-haber-alg%C3%BAn-negocio-para-que-pueda-llamarse-l%C3%B3gica-de-negocio):
> 
> > En inglés se usa a veces business para indicar la parte importante de algo, o la que hace el trabajo.
> 
> No tiene nada que ver con el "conocimiento" de ningún aspecto del problema o la "confianza" del usuario, sino con el procesamiento no trivial de datos para solucionar el problema del cliente.
> 
> También sería conveniente que cambiaras el título del PR siguiendo las instrucciones, y lo que realmente contiene (que ya no es un juego de rol)

2023-09-18 16:35 UTC, JJ requested changes
Aparte de lo comentado, no está claro que haya una lógica de negocio más allá de "haz compras semanales". Así mismo me gustaría señarte, de [errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md#con-respecto-a-los-problemas-enviados)

> El juego de rol de la primera sesión es una forma de aplicar design thinking y el proceso de empatía para encontrar y describir un problema a resolver. Si no se ha participado en el juego de rol, o el problema no se ha validado, design thinking sigue siendo válido; en general, va a ser muy difícil que sin un proceso formal se halle y describa un problema, y que sea válido.

En [el guión de la práctica](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) dice:

> En general, encontrar un proyecto que se pueda desarrollar en la asignatura es una cuestión personal, sobre todo porque es necesario que se trate de un proyecto donde uno tiene algún interés y conocimiento, y pueda identificar claramente cuales son los retos y qué es lo que funciona y aporta valor al cliente (que puede ser uno mismo). La metodología denominada [design thinking](https://jj.github.io/IV/preso/design-thinking.html) te da una serie de pasos para poder entender posibles contextos en los cuales existe un problema, definirlo y proponer posibles soluciones.

En general, lo que se trata de transmitir en esta asignatura es una mentalidad (la ágil) pero también una serie de procesos formales para definir y resolver problemas en ingeniería informática. Entender y aplicar esas metodologías es lo esencial para poder alcanzar este objetivo (y el resto)

2023-09-18 17:33 UTC, javigp2002 commented
@JJ He intentado darle una vuelta a la descripción del problema enfocándolo en la necesidad de llevar una dieta variada y, de ahí, sale el proyecto. Por otro lado, la lógica de negocio no quiero que se vea como "haz la compra" sino minimizar el tiempo de pensar en una buena dieta, minimizar los viajes al supermercado y controlar lo que cada uno come.

2023-09-18 17:42 UTC, JJ commented
> @JJ He intentado darle una vuelta a la descripción del problema enfocándolo en la necesidad de llevar una dieta variada y, de ahí, sale el proyecto. Por otro lado, la lógica de negocio no quiero que se vea como "haz la compra" sino minimizar el tiempo de pensar en una buena dieta, minimizar los viajes al supermercado y controlar lo que cada uno come.

Eso tampoco es la lógica de negocio, es el resultado que quieres obtener. La lógica de negocio tendría que ser lo necesario para alcanzar ese resultado, y si quieres que sea válida para la asignatura tiene que tener una cierta complejidad.

2023-09-18 17:51 UTC, JJ requested changes
Leyendo el problema da la impresión de que tienes claro lo que quieres hacer (un buscador de recetas o algo así) y que *trabajas hacia atrás* tratando de buscar un problema para el cual sea solución. Es una metodología como otra cualquiera, pero desgraciadamente es una metodología que no funciona porque da lugar a formulaciones que son difíciles de comprender.
Como en cualquier otro aspecto de un desarrollo en ingeniería, hay que seguir las buenas prácticas para poder aprovechar el tiempo de forma eficiente. Como profesor te sugiero que uses la fase de ideación y empatía de la metodología *design thinking* para llegar a esto, que es una de las metodologías generalmente aceptadas para esta tarea.
Por supuesto, sabiendo *por qué* hay que definir un problema claramente (para poder definir claramente los subproblemas que plantean en el siguiente objetivo, y modelizarlo en el número dos), puedes usar cualquier otra metodología que consideres conveniente.
Pero *no usar ninguna metodología* no te acerca a la consecución del objetivo.
Recuerda en todo caso que en esta asignatura el enfoque es entender y poner en práctica una serie de buenas prácticas de diseño, implementación y despliegue de producto en la nube. *Primero* hay que intentar asimilar y aplicar esas metodologías (en este paso, la que te he comentado), y a continuación hacer la entrega. Por eso te reitero mi ofrecimiento a que repitamos el juego (que implementa esta metodología) el jueves en clase, o si lo deseas, plantéalo en en grupo de Telegram porque hay otras personas en tu misma situación, e igual os podéis retroalimentar en la ETSIIT o por videoconferencia para desbloquear este logro.

2023-09-18 17:51 UTC, JJ commented on README.md
> +El usuario vive solo y no quiere gastar tiempo en decidir que cocinar e ir previamente al supermercado a comprar los productos necesarios cada vez que quiere comer. Asimismo, esto conlleva a la comid
El problema sigue sin estar definido con precisión, de forma que una persona ajena a la formulación del mismo (el desarrollador del juego de rol) pueda ponerse a trabajar para intentar solucionarlo.

2023-09-20 08:58 UTC, javigp2002 commented
@JJ He realizado con unos compañeros de nuevo el juego de rol pero esta vez con otro problema.

2023-09-20 09:02 UTC, JJ requested changes
El problema puede ser válido, siempre que identifiques el verdadero problema. ¿Cómo se sabe qué gasolinera es la más barata? ¿Qué tipo de procesamiento sería necesario para ello?

2023-09-20 09:02 UTC, JJ commented on README.md
> +El usuario, un estudiante, se acaba de independizar y su medio de transporte habitual y hobby es la moto. Sin embargo, con la subida de los carburantes se dedica a buscar las gasolineras más baratas
Del [guión del objetivo 0](http://jj.github.io/IV/documentos/proyecto/0.Repositorio). Sobre la posible solución al problema:

> No incluir palabras como “buscar”, “dar de alta”, “poner en contacto”, “recuperar”, “integrar”, “alertar”, “comunicar”.

2023-09-20 10:14 UTC, javigp2002 commented
@JJ La gasolinera más barata se encuentra en la Base de Datos donde tenemos guardadas todas las gasolineras de España así como el precio de sus distintos carburantes. Por ello, el procesamiento seria a través de un tipo de algoritmo de ordenación filtrando, previamente, el carburante que utiliza el vehículo y teniendo diferentes aspectos en cuenta: el precio, consumo del vehículo distancia entre los dos puntos que tenemos...

2023-09-20 10:17 UTC, JJ commented
> @JJ La gasolinera más barata se encuentra en la Base de Datos donde tenemos guardadas todas las gasolineras de España así como el precio de sus distintos carburantes. Por ello, el procesamiento seria a través de un tipo de algoritmo de ordenación filtrando, previamente, el carburante que utiliza el vehículo y teniendo diferentes aspectos en cuenta: el precio, consumo del vehículo distancia entre los dos puntos que tenemos...

O sea, que se trata de una búsqueda. Del [guión de este objetivo](http://jj.github.io/IV/documentos/proyecto/0.Repositorio)

> Lo esencial siempre es que la aplicación incluya un valor añadido en forma de lógica de negocio, y que se describa correctamente el problema a solucionar de forma que haga falta tal lógica de negocio para solucionarlo.

Y sobre las posibles soluciones (que en principio no formarían parte de este objetivo salvo que haga falta aclararlo), la lógica de negocio debe:

> **No** incluir palabras como “buscar”, “dar de alta”, “poner en contacto”, “recuperar”, “integrar”, “alertar”, “comunicar”.

2023-09-20 10:28 UTC, javigp2002 commented
@JJ  No es una búsqueda como tal, tenemos unos datos y según la información proveniente del usuario se filtrarían esos datos, calcularíamos el coste supuesto del trayecto y generaríamos nueva información (costes, porcentaje de eficiencia o incluso el tiempo extra que supondría este desvío) que pueda utilizar de la mejor manera posible.

2023-09-20 10:37 UTC, JJ commented
> @JJ No es una búsqueda como tal, tenemos unos datos y según la información proveniente del usuario se filtrarían esos datos, calcularíamos el coste supuesto del trayecto y generaríamos nueva información (costes, porcentaje de eficiencia o incluso el tiempo extra que supondría este desvío) que pueda utilizar de la mejor manera posible.

Gracias por contestar y por seguirlo intentando. Te rogaría que, en ese caso, explicaras claramente el contexto del problema, de qué "datos" se trata, y en resumen cuál es el problema que se está tratando de resolver; hazlo en el propio README, que es donde debe quedar plasmado una vez se fusione.

2023-09-20 10:58 UTC, javigp2002 commented
@JJ He añadido al [https://github.com/javigp2002/LazyFood/pull/1/commits/975654665958ada541a663f6095b8473a111108c](README) una mayor descripción del problema que da lugar a lo comentado previamente y especificado al inicio del PR en las preguntas.

PD: no se si irá bien la URL pero me ha parecido oportuno

2023-09-20 11:15 UTC, JJ commented
> @JJ He añadido al [README](https://github.com/javigp2002/LazyFood/pull/1/commits/975654665958ada541a663f6095b8473a111108c) una mayor descripción del problema que da lugar a lo comentado previamente y especificado al inicio del PR en las preguntas.
> 
> PD: no se si irá bien la URL pero me ha parecido oportuno

Para enlazar un commit específico no tienes más que copiar los 7 números que aparecen en el listado, como arriba. En todo caso, como ves todo lo que se sube a una rama está ya enlazado, así que en realidad no es necesario.

2023-09-20 11:27 UTC, JJ requested changes
Gracias por seguirlo intentando, creo que al menos tenemos identificado el contexto del problema y aproximadamente el problema. El problema es que hace falta precisar un poco más para progresar al siguiente, sobre todo tratando de apuntar a las posibles soluciones.
En el mismo guión figura que una posible lógica de negocio podría incluir procesos como "extraer". En la ficha del juego de rol se sugería usar fuentes de información poco estructuradas. ¿Puede ser que la información de las gasolineras, el precio, o ambas esté en fuentes poco estructuradas y por tanto *el problema* sea extraer esa información para ponerla en un formato (base de datos, y más adelante un API) donde pueda estar fácilmente disponible?
Si está bien estructurada, pero no se actualiza con frecuencia, ¿podría aplicarse algún algoritmo de predicción para predecir cuál es el precio ahora? (En todo caso sería un algoritmo que tú tendrías que programar)

2023-09-20 11:27 UTC, JJ commented on README.md
> +El usuario, un estudiante, se acaba de independizar y su medio de transporte habitual y hobby es la moto. Sin embargo, con la subida de los carburantes se dedica a buscar las gasolineras más baratas
Gracias por aclarar el problema. El problema ahora está más o menos claro, pero para alcanzar el objetivo, todavía habría un par de obstáculos.

1. Una aplicación móvil podría perfectamente resolverlo, sin necesidad de que esté alojada en la nube. Si usa datos que están ya disponibles a través de un API (o de cualquier otra forma), la forma más optima de tratarlos es en el cliente.
2. Este es mayor, me temo. Como pone en [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio), no serán adecuados *Todos los problemas que requieran entradas físicas; todos aquellos en los que el usuario o cliente tenga que introducir mucha información. En general, todo problema que no se entienda bien.*. En este caso, sin saber la localización del dispositivo, el consumo previsto hasta llegar a cada una de las gasolineras, y el estado del depósito actualmente (para ver si llenarlo conllevaría más ahorro que ir hacia una gasolinera determinada), es imposible resolverlo.
3. Finalmente, también en el guión enlazado dice que una lógica de negocio puede ser no adecuada si "Si requiere un modelo complejo del programa, o un algoritmo complejo para trabajar con ella, puede ser un problema, porque, insisto, lo tiene que programar el estudiante. Si requiere predicción y por tanto un algoritmo de machine learning, doble problema, porque requiere conjunto de entrenamiento y programar el algoritmo. Se pueden usar, sin embargo, modelos ya entrenados siempre que esos modelos los programe uno." En este caso, tendrías al menos que tener una heurística que filtrara, de antemano, las gasolineras sobre las que vas a buscar. Dependiendo de la información que tengas sobre las mismas, esto puede ser más fácil o más complejo. REcuerda que la lógica de negocio vas a tener que programarla tú.

2023-09-20 12:17 UTC, javigp2002 commented
@JJ La fuente de las gasolineras y sus precios se encuentra bien estructurada en un JSON que se actualiza casi a diario. No obstante, el problema que planteaba no iba tanto con la extracción de la información sino con un algoritmo que calculara y ofreciera las mejores opciones de las gasolineras.

Por otro lado, comentando los obstaculos:
1.- La aplicación móvil podría resolverlo pero según mis búsquedas lo más común en estos casos son páginas que ofrezcan información sin ningún tipo de algoritmo y, ahí es donde yo trabajaría (calculando y generando una optimización del tiempo y costes según la localización)
2.- Entendía que las entradas físicas no podían ser muchas y no que se estableciera la ausencia de ellas. Fallo mio. No obstante, podría usar los localizadores propios del dispositivo en el que se encuentra, ¿no? Asimismo, la predicción se podría hacer en base a la media que establece la gente e, incluso, podría ofrecer alternativas sin conocer el estado del deposito según la cantidad de litros que vaya a necesitar, es decir, cuando muestro los resultados y sus costes estaría también mostrando según los litros añadidos.
3.- Yo no pretendo realizar ninguna predicción sobre el precio de la gasolina (que es [bastante complejo](https://www.aop.es/sector/precio-de-los-combustibles/) ). Sino utilizar la información abierta que provee el Ministerio y realizar calculos a través de ello.

No se si me estoy explicando o ya me estoy metiendo en terreno pantanoso pero las ideas que le doy siguen siendo las mismas que cuando plantee mi problema con mis compañeros aunque no creo que me este expresando con claridad.

2023-09-20 12:45 UTC, JJ commented
> @JJ La fuente de las gasolineras y sus precios se encuentra bien estructurada en un JSON que se actualiza casi a diario. No obstante, el problema que planteaba no iba tanto con la extracción de la información sino con un algoritmo que calculara y ofreciera las mejores opciones de las gasolineras.

¿Y la localización?
> 
> Por otro lado, comentando los obstaculos: 1.- La aplicación móvil podría resolverlo pero según mis búsquedas lo más común en estos casos son páginas que ofrezcan información sin ningún tipo de algoritmo y, ahí es donde yo trabajaría (calculando y generando una optimización del tiempo y costes según la localización)

Si la información está en un JSON, desplegarlo en la nube no aportaría nada más que costes para la persona que tenga la aplicación. En todo caso, no sería un gran obstáculo y por eso no voy a decir que el objetivo no está superado.

> 2.- Entendía que las entradas físicas no podían ser muchas y no que se estableciera la ausencia de ellas. Fallo mio. No obstante, podría usar los localizadores propios del dispositivo en el que se encuentra, ¿no? Asimismo, la predicción se 

NO, no puedes, porque vamos a trabajar sólo con servidores. En todo caso, en la asignatura se pide que os concentréis en la lógica de negocio y vamos a suponer que tienes la localización. ¿Cómo calculas el camino óptimo a cada una de las gasolineras? ¿Tienes información sobre carreteras?

> podría hacer en base a la media que establece la gente e, incluso, podría ofrecer alternativas sin conocer el estado del deposito según la cantidad de litros que vaya a necesitar, es decir, cuando muestro los resultados y sus costes estaría también mostrando según los litros añadidos. 

Vamos a suponer que sólo permites localizaciones fijas, y sabes el kilometraje y tipo de consumo a cada una de las gasolineras; también los litros que quieres llenar. 

> 3.- Yo no pretendo realizar ninguna predicción sobre el precio de la gasolina (que es [bastante complejo](https://www.aop.es/sector/precio-de-los-combustibles/) ). Sino utilizar la información abierta que provee el Ministerio y realizar calculos a través de ello.

Te recuerdo que se trata de una lógica de negocio con una mínima complejidad. Si se trata de hacer dos sumas y dos multiplicaciones (precio de la gasolina + costes de llegar a la misma) y hallar el mínimo, no se trata de una lógica de negocio con la mínima complejidad. Ni siquiera si tenemos en cuenta un filtro de todas las gasolineras del ministerio teniendo en cuenta el código postal (o lo que sea que hayamos establecido como posición). Si en los cálculos necesarios para todo eso hubiera que hacer alguna extracción de información o procesamiento de cadenas o de lo que fuera, sería otro tema diferentes. Pero problemas con un procesamiento simple suelen tener modelos simples, y por tanto no permiten aprender nada en los objetivos 3 y 4, por lo que prefiero atajarlos en este objetivo para emplear el resto del tiempo de forma más eficiente.

> 
> No se si me estoy explicando o ya me estoy metiendo en terreno pantanoso pero las ideas que le doy siguen siendo las mismas que cuando plantee mi problema con mis compañeros aunque no creo que me este expresando con claridad.

Yo creo que más o menos lo entiendo, pero sigue habiendo más o menos  los problemas que te comenté desd el principio. Tendrás que tratar de reformular el problema, o de formular un aspecto del problema, que *sí* incluya procesamiento complejo, la aplicación de algún algoritmo, o de expresiones regulares o algún tipo de heurística para extraer información de fuentes con poca estructura.

2023-09-21 08:19 UTC, javigp2002 commented
@JJ Nuevo problema creado relacionado con La Liga Fantasy

2023-09-21 11:36 UTC, JJ requested changes
Mira el [último error frecuente](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md) (fresco de hoy):

> Escribir el problema sobreentendiendo lo que se ha hablado en clase con el profesor. Se debe entregar de forma que incluso un profesor olvidadizo, u otro, entienda de qué se está hablando.

2023-09-21 11:36 UTC, JJ commented on README.md
> +El usuario, un jugador de La Liga Fantasy, juega con sus amigos todos los años a este juego de móvil. Sin embargo, no está completamente absorbido por el mundo técnico del fútbol y tampoco sigue a lo
Por favor, explica un poco mejor el contexto, qué datos hay y demás. No supongas que tengo presente lo que hemos hablado en clase, o que me voy a acordar cuando revise los objetivos siguientes (yo o quien sea)

2023-09-21 11:46 UTC, javigp2002 commented
@JJ Creo que ya he clarificado el problema para que alguien ajeno, incluso al fútbol y este mundo, lo comprenda.

2023-09-21 11:58 UTC, JJ approved these changes
:+1:

2023-09-21 12:14 UTC, merged