[IV-23-24] Objetivo 3
javigp2002/LazyFood pull request #18
Opened 2023-10-28 11:45 UTC by javigp2002

* [X] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [X] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [X] ¿Ese issue está asignado a un milestone?
* [X] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [X] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [X] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [X] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [X] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2023-10-29 11:23 UTC, giorgiogiovanni requested changes
Te sugiero pequeñas revisiones. En general el tema de los espacios o las líneas en blanco que te comento son aplicables en muchos sitios...

2023-10-29 11:23 UTC, giorgiogiovanni commented on Docs/gestor_dependencias.md
> +Al haber elegido **Deno** como la opción más equilibrada el siguiente punto es elegir su gestor de dependnecias. No obstante, como hemos comentado en su elección, este no necesita un gestor dependenc
Aunque no haya pasado el objetivo, dado que me @JJ me añadió, aprovecho para comentarte/sugerirte algunas pequeñas correcciones 
dependnecias -> dependencias

2023-10-29 11:23 UTC, giorgiogiovanni commented on Docs/gestor_tareas.md
> +Inspirado en Make, Rakke y Jake este es un task-runner creado para deno donde los “DrakeFiles” son los módulos  de Deno los cuales importan el módulo, definen y registran las tareas y las ejecutan. S
Doble espacios entre palabras.
En general además es una buena practica hacer saltos de linea cada X caracteres (tradicionalmente 80).
Además así es mas sencillo también identificar líneas donde se sugieren los cambios.

2023-10-29 11:23 UTC, giorgiogiovanni commented on Docs/runtime.md
> +Los criterios de decisión pueden y crean deudas técnicas en torno a todo el trabajo, esto conlleva que la elección de cualquier parte de nuestra app ha de ser bien planteada.
Los _titulos_ o apartados, aunque md los formatea correctamente, suelen separarse de los párrafos mediante
líneas en blanco

2023-10-29 11:23 UTC, giorgiogiovanni commented on Docs/runtime.md
> +Basado en Rust se creo con el pensamiento de desbancar a Node.js. Este tiene un ecosistema estable con suficientes desarrolladores que cumplen la función para poder resolver problemas comunes y bugs
creó

2023-10-29 11:46 UTC, javigp2002 commented on Docs/gestor_dependencias.md
> +Al haber elegido **Deno** como la opción más equilibrada el siguiente punto es elegir su gestor de dependnecias. No obstante, como hemos comentado en su elección, este no necesita un gestor dependenc
Resuelto en [e900bad](https://github.com/javigp2002/LazyFood/pull/18/commits/e900bad474e8296c7a63ab421b5ed5ff62df0bb8)

2023-10-29 11:46 UTC, javigp2002 commented on Docs/gestor_tareas.md
> +Inspirado en Make, Rakke y Jake este es un task-runner creado para deno donde los “DrakeFiles” son los módulos  de Deno los cuales importan el módulo, definen y registran las tareas y las ejecutan. S
Resuelto en [e900bad](https://github.com/javigp2002/LazyFood/pull/18/commits/e900bad474e8296c7a63ab421b5ed5ff62df0bb8)

2023-10-29 11:46 UTC, javigp2002 commented on Docs/runtime.md
> +Basado en Rust se creo con el pensamiento de desbancar a Node.js. Este tiene un ecosistema estable con suficientes desarrolladores que cumplen la función para poder resolver problemas comunes y bugs
Resuelto en [e900bad](https://github.com/javigp2002/LazyFood/pull/18/commits/e900bad474e8296c7a63ab421b5ed5ff62df0bb8)

2023-10-29 11:53 UTC, giorgiogiovanni requested changes
Te vuelvo a añadir las sugerencias para los saltos de línea. Disculpa porque es un poco coñazo pero creo que ha sido fallo mio que no lo he sabido expresar bien antes para que revisaras esos detallillos en más sitios. Por lo demás no creo que pueda aportar mucho más

2023-10-29 11:53 UTC, giorgiogiovanni commented on Docs/runtime.md
> +Es el claro ganador de los runtime en cuanto a popularidad y cantidad de información que se puede
añade salto de linea bajo titulo "##"

2023-10-29 11:53 UTC, giorgiogiovanni commented on Docs/runtime.md
> +Basado en Rust se creó con el pensamiento de desbancar a Node.js. Este tiene un ecosistema estable con
idem. salto de línea

2023-10-29 11:53 UTC, giorgiogiovanni commented on Docs/runtime.md
> +Implementado por Zig es también compatible con la mayoría de paquetes de Node.js y mucho más rápido que
idem

2023-10-29 11:53 UTC, giorgiogiovanni commented on Docs/runtime.md
> +Finalmente, la elección más equilibrada es Deno debido a su estabilidad y en creciente comunidad, la
idem

2023-10-29 11:53 UTC, giorgiogiovanni commented on README.md
> +### Clase Equipo
separa los titulos por línea en blanco

2023-10-29 11:57 UTC, javigp2002 commented
@giorgiogiovanni Gracias por tus comentarios. Muy útiles 💯

2023-10-29 11:57 UTC, javigp2002 commented on Docs/runtime.md
> +Es el claro ganador de los runtime en cuanto a popularidad y cantidad de información que se puede
Resuelto en [c731912](https://github.com/javigp2002/LazyFood/pull/18/commits/c7319121496a437684d245a1cea3f612c5c056a3).

2023-10-29 11:57 UTC, javigp2002 commented on Docs/runtime.md
> +Basado en Rust se creó con el pensamiento de desbancar a Node.js. Este tiene un ecosistema estable con
Resuelto en [c731912](https://github.com/javigp2002/LazyFood/pull/18/commits/c7319121496a437684d245a1cea3f612c5c056a3).

2023-10-29 11:57 UTC, javigp2002 commented on Docs/runtime.md
> +Implementado por Zig es también compatible con la mayoría de paquetes de Node.js y mucho más rápido que
Resuelto en [c731912](https://github.com/javigp2002/LazyFood/pull/18/commits/c7319121496a437684d245a1cea3f612c5c056a3).

2023-10-29 11:57 UTC, javigp2002 commented on Docs/runtime.md
> +Finalmente, la elección más equilibrada es Deno debido a su estabilidad y en creciente comunidad, la
Resuelto en [c731912](https://github.com/javigp2002/LazyFood/pull/18/commits/c7319121496a437684d245a1cea3f612c5c056a3).

2023-10-29 11:57 UTC, javigp2002 commented on README.md
> +### Clase Equipo
Resuelto en [c731912](https://github.com/javigp2002/LazyFood/pull/18/commits/c7319121496a437684d245a1cea3f612c5c056a3).

2023-10-29 12:08 UTC, giorgiogiovanni approved these changes
Por mi parte es correcto

2023-10-29 12:19 UTC, javigp2002 commented
@JJ listo para revisión.

2023-10-30 08:14 UTC, JJ approved these changes
:+1: Ya van tres con esto... Dejo esto como aviso a navegantes, que en los siguientes se va a tener que mostrar un poco más empeño en la búsqueda de los fuentes y la justificación; otra vez lo mismo y la misma decisión no necesariamente van a tener el mismo resultado de aprobación.
En todo caso, corrige lo indicado y muchas gracias a @giorgiogiovanni por el trabajo realizado (aunque no le tocaba)

2023-10-30 08:14 UTC, JJ commented on Docs/runtime.md
> +que se encuentra en Beta y no en producción lo que está resultando en bugs constantes por parte de los
Ya no está en beta. Por favor, mirad fuentes actualizadas.

2023-10-30 08:14 UTC, JJ commented on Docs/gestor_tareas.md
> +Hace 3 meses se anuncio la entrada de este task-runner como nueva herramienta para Deno el cual tiene una interfaz para poder realizar las tareas de una manera más sencilla e intuitiva, así como en s
Podíais enlazar las herramientas de las que habláis...

2023-11-02 12:03 UTC, merged