[IV-23-24] Objetivo 4
javigp2002/LazyFood pull request #19
Opened 2023-11-02 12:09 UTC by javigp2002

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se    esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en  este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases módulos o paquetes más fundamentales frente a otros, movidos a otro PMV/Hito?
* [ ] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por delante?
* [ ] ¿Se han documentado las elecciones de biblioteca de aserciones y del de *test runner*?
* [ ] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo `unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [ ] ¿Se han testeado también las excepciones?

2023-11-12 16:44 UTC, Morad02 requested changes
En general los commits y los issues siguen las buenas prácticas y están bastante bien. Modificando lo comentado creo que se estaría más cerca del aprobado.

2023-11-12 16:44 UTC, Morad02 commented on Docs/eleccion_test.md
> +## Herramientas CLI
Se debería explicar el por qué de esta elección.

2023-11-12 16:44 UTC, Morad02 commented on deno.json
> -
¿Estás usando el linter?

2023-11-12 16:44 UTC, Morad02 commented on test/equipo_test.ts
> +    function esJugador(jugador:Jugador): boolean {
Si no recuerdo mal, la biblioteca de aserciones ya te incluye una función para comprobar si es una instancia de algo.

2023-11-12 16:44 UTC, Morad02 commented on test/equipo_test.ts
> +    beforeAll(() => {
Estás declarando muchas variables que no son necesarias

2023-11-12 16:44 UTC, Morad02 commented on test/equipo_test.ts
> +        assert(jugador === equipoDistintaPuntuacion.getJugadores()[0]);
Veo que estás comparando el resultado con la salida esperada. Esto no es del todo correcto, ya que si por ejemplo cambias la lógica de negocio ya no se pasarían los tests. Lo que se tiene que hacer es definir qué es un jugador óptimo y que te compruebe que el jugador que te ha devuelto es un jugador óptimo.

2023-11-12 17:26 UTC, javigp2002 commented on Docs/eleccion_test.md
> +## Herramientas CLI
Es cierto, se ha explicado en [2a33d0d](https://github.com/javigp2002/LazyFood/pull/19/commits/2a33d0d18038ba1e63f81c679b2cbd794c97a854)

2023-11-12 17:26 UTC, javigp2002 commented on deno.json
> -
No, y ya lo elimine previamente 😄

2023-11-12 17:27 UTC, javigp2002 commented on test/equipo_test.ts
> +    function esJugador(jugador:Jugador): boolean {
Efectivamente existia, muchas gracias, arreglado en [8bb5f09](https://github.com/javigp2002/LazyFood/pull/19/commits/8bb5f091c5d94fb04b1163d242fe19ef4d20ec9c)

2023-11-12 17:27 UTC, javigp2002 commented on test/equipo_test.ts
> +    beforeAll(() => {
Ciertamente había muchas innecesarias y otras que se utilizaban tontamente sin dar lugar a que se viera el verdadero funcionamiento del test. Arreglado en [0b9216b](https://github.com/javigp2002/LazyFood/pull/19/commits/0b9216b6bd177ddf5227f161420f8a57e5e0cf9a).

2023-11-12 17:32 UTC, javigp2002 commented on test/equipo_test.ts
> +        assert(jugador === equipoDistintaPuntuacion.getJugadores()[0]);
Sí, cómo puse en [2768ebc](https://github.com/javigp2002/LazyFood/pull/19/commits/2768ebc5211a14a2c0e205165cc55244eb2272b9) es cierto que lo hago pero hablando con el profesor en una heurística no es tan fácil comprobar si un jugador es óptimo o no con una función externa debido a que la misma heurística deberá tomar "decisiones" y puntuar los jugadores según un algoritmo dado. Es decir, estos test de la lógica de negocio deben cumplirse siempre puesto que son los casos extremos donde conocemos claramente el jugador que va a salir y así poder comprobarlo :monocle_face:.

2023-11-12 17:34 UTC, javigp2002 commented
@Morad02 Muchísimas gracias por dedicarme el tiempo que esto conlleva, se de buena mano que revisar es una tarea ardua y más si además eres el primero que lo pasa. Ya he corregido todo lo que me has puesto o te he respondido en aquellos apuntes que me has dado. 
Échale un 👁️ cuando puedas y tengas tiempo.

2023-11-12 17:45 UTC, Morad02 approved these changes
Buen trabajo y gracias por tu consideración. Espero que te vaya bien!

2023-11-12 17:46 UTC, javigp2002 commented
@JJ Listo para revisión debido a que ya ha sido aceptada por @Morad02 . :fire:

2023-11-13 09:00 UTC, JJ approved these changes
Algunos "nits" sobre el código, pero en general correcto. Gracias a @Morad02 por la revisión.

2023-11-13 09:00 UTC, JJ commented on test/equipo_test.ts
> +            new Jugador("Gavi", [1,1,1,1], [10000000, 10000000, 10000000, 10000000], barcelona),
Estos datos estarían mejor en un fichero, porque si tienes qeu añadir casos de test es mejor el fichero que el código.

2023-11-16 08:32 UTC, javigp2002 commented on src/equipo.ts
> +            let diferencia_dificultad_equipo = 0.1;
Resuelto en  [591636c](https://github.com/javigp2002/LazyFood/pull/19/commits/591636cfe9464aa5fb469cece8bd2ce63eca1728)

2023-11-16 08:32 UTC, javigp2002 commented on src/equipo.ts
> +                diferencia_dificultad_equipo = -0.1
Resuelto en [591636c](https://github.com/javigp2002/LazyFood/pull/19/commits/591636cfe9464aa5fb469cece8bd2ce63eca1728)

2023-11-16 08:34 UTC, javigp2002 commented on src/jugador.ts
> +        for (let i=0; i<this.getValorPorJornada().length; i++)
Resuelto en [900bebb](https://github.com/javigp2002/LazyFood/pull/19/commits/900bebb930e5d77630bc7de3ac9c40bb22f75527)

2023-11-16 08:34 UTC, javigp2002 commented on src/equipo.ts
> +        for (let i=0; i<this.jugadores.length; i++){
Resuelto en [9bfbc87](https://github.com/javigp2002/LazyFood/pull/19/commits/9bfbc87e53367f950178116ab480d2d4ce0605e0)

2023-11-16 15:09 UTC, javigp2002 commented on test/equipo_test.ts
> +            new Jugador("Gavi", [1,1,1,1], [10000000, 10000000, 10000000, 10000000], barcelona),
Ciertamente, hecho en 12f9572

2023-11-16 15:10 UTC, merged