Creación de Personas, Milestones e Historias
javigp2002/LazyFood pull request #2
Opened 2023-09-23 10:09 UTC by javigp2002

Se han especificado y argumentado las Personas, Milestones e Historias

2023-09-25 12:13 UTC, JJ requested changes
Las HUs serían bastante correctas, aunque añadirles contexto no estaría mal (por ejemplo, de dónde se extraen los datos, o qué juego en concreto se va a hacer, o si son todos los juegos), pero los milestones tendrías que tratar de expresar con más precisión qué se busca en cada uno de forma que cualquier pesona pueda entenderlo.

2023-09-25 12:13 UTC, JJ commented on Docs/Milestones.md
> +Debemos tener definidos tanto los jugadores, valores de mercado y puntuaciones obtenidas en las últimas 4 jornadas y su posición.
No debes poner explícitamente en qué consiste el modelo del problema. Tampoco queda claro en este contexto qué son "los jugadores".

Un modelo no consiste en crear variables que se llamen igual, sino en modelizar esos objetos del espacio del problem con las restricciones que sean convenientes.

2023-09-25 12:13 UTC, JJ commented on Docs/Milestones.md
> +Dados todos los jugadores de La Liga que conseguiremos un equipo de 11 jugadores con los mejores jugadores posibles que asegure la lógica de negocio.
Por favor, expresa las cosas correctamente. "Que asegure la lógica de negocio" es difícil de comprender.

2023-09-25 12:13 UTC, JJ commented on Docs/Milestones.md
> +## [M2]: Búsqueda real del mejor equipo
Los milestones siempre son productos; trata de especificar claramente qué producto estás buscando. Lo que estás diciendo es solamente qué lo hace viable (ser capaz de hacer esa búsqueda, aunque deberías especificar qué la hace "real" y la otra "de mentirijillas")

2023-09-25 16:03 UTC, JJ requested changes
Trata de ser preciso con el contexto, por fafor. Ayudaría que escribieras el *user journey*, donde diga cómo se trabaja en la liga fantasy y qué dilemas se presentan. Por ejemplo, ¿todas las jornadas se cambian todos los jugadores? ¿Estás buscando estrategias para cambiar jugadores? ¿Para comprar el equipo al principio de la liga? ¿Serían dos HUs diferentes?

2023-09-25 16:03 UTC, JJ commented on Docs/Historias.md
> +Juan, además de buscar jugadores óptimos para su equipo, desea encontrar jugadores de una posición concreta para su equipo.
Imagínate que quien desarrolla esto es, no sé, de Vanuatu y que allí sólo saben de béisbol. ¿Qué significa "posición" en un equipo? Así mismo, ¿estamos hablando sólo de *fantasy football?

2023-09-25 16:03 UTC, JJ commented on Docs/Historias.md
> +Pedro busca poder cambiar de equipo cada jornada pudiendo cambiar de formación.
Antes hablabas de "posición", ahora de "formación".

Recuerda que estos son documentos de trabajo. Por favor, trata de explicar todo lo que puedas el contexto.

2023-09-25 16:03 UTC, JJ commented on Docs/Milestones.md
> +## [M2]: Búsqueda real del mejor equipo
:arrow_up:

2023-09-25 16:03 UTC, JJ commented
@marioguisado quizás podrías revisar este PR. Por favor, si puedes/quieres confirmadlo para que yo no lo revise hasta que tú des tu aprobación.

2023-09-25 17:34 UTC, MarioGuisado commented
En el milestone 0, se pide que se genere el modelo del problema a través de las historias de usuario (lo cual es correcto), pero se indica que para ser alcanzado se deben identificar únicamente los datos de los jugadores. El modelo del problema no solo son las identidades que lo forman, y sus datos, sino también las relaciones que establecen y sus restricciones. En cuanto a los otros milestones, no creo que planificar más allá del milestone 1 o 2 como mucho sea viable. Además, sigues sin especificar el producto que se busca en cada uno.

2023-09-25 22:05 UTC, javigp2002 commented
@MarioGuisado Ya he corregido los milestones para que se adecuen a lo requerido. Comprueba que he seguido tus consejos.

2023-09-26 07:49 UTC, MarioGuisado commented
@JJ parece que los hitos ya han sido corregidos. Creo que está listo para su revisión.

2023-09-26 07:50 UTC, JJ commented
> @JJ parece que los hitos ya han sido corregidos. Creo que está listo para su revisión.

Por favor, aprobadlo explícitamente en el review y dejad que la persona del repo pida revisión.

2023-09-26 07:53 UTC, MarioGuisado approved these changes

2023-09-26 08:12 UTC, JJ requested changes
Has hecho un buen trabajo (y @MarioGuisado también) revisando y mejorando, sobre todo con la introducción del user journey; desgraciadamente, no has adaptado las historias de usuario al user journey, resultando que hay una serie de problemas y ambigüedades que impiden que se pueda desarrollar correctamente usándolo.

Trata de mirar también todos los comentarios que haya, y reaccionar al respecto.

2023-09-26 08:12 UTC, JJ commented on Docs/Historias.md
> +## HU01: Antonio quiere conocer la puntuación óptima de los futbolistas
Por favor, tratad de ser precisos en la descripción. "Conocer" es "averiguar" o hallar algo que no se sabe. Si hablas de "los futbolistas" estás diciendo que para un grupo de futbolistas establecido y determinado, quieres averiguar cuál es esa puntuación.

Trata de explicar claramente lo que se busca, para alinearlo con la descripción que tienes más abajo.

2023-09-26 08:12 UTC, JJ commented on Docs/Historias.md
> +Antonio es un jugador de _La Liga Fantasy_ que quiere conocer la puntuación óptima de los futbolistas con un presupuesto normal de forma que pueda los encontrar buenos y baratos para su equipo. Por e
Trata de evitar errores gramaticales ("los evitar") y una vez más, explicar claramente lo que hace falta. Básicamente, lo que tiene (¿presupuesto? ¿una lista de jugadores con sus precios y otras características?) y lo que quiere (¿maximizar alguna suma de alguna característica con un precio determinado?)

Trata también de explicar los detalles. ¿Cada jugador puede estar solamente en un equipo? ¿Lo único que hay para juzgarlo es la puntuación? ¿Qué implica comprarlo? ¿Tienes que vender otro? ¿Hay que decidir entonces cuál vender para poder comprar otro?

2023-09-26 08:12 UTC, JJ commented on Docs/Historias.md
> +1. Al usuario se le da un equipo completo de futbolistas de _La Liga Fantasy_ que suman un presupuesto de 100Millones de monedas del juego.
¿Se le asignan aleatoriamente?

2023-09-26 08:12 UTC, JJ commented on Docs/Personas.md
> +## Pedro
Pedro ¿qué historia de usuario tiene?

2023-09-26 10:23 UTC, JJ requested changes
Con el user journey creo que voy entendiendo mejor el problema, sin embargo me faltan todavía algunos datos del contexto. El principal, es que entiendo que la puntuación y el precio son más o menos equivalentes, por lo que la única forma de maximizar la puntuación es maximizar el precio, en cuyo caso no tenemos realmente una lógica de negocio para trabajar con ella. Debe haber algún otro factor que te permita optimizar la inversión, en función de las prestaciones futuras o de otros factores: que vaya a jugar en casa o fuera, por ejemplo, no sé.

En todo caso, el *user journey* te debería servir para aclarar qué problemas puede ser más sencillo solucionar, una vez aclarado eso. Por ejemplo, se me ocurre que seleccionar el equipo entre todos los que tienes puede ser el más sencillo, siempre por supuesto que aclares qué estás optimizando en este caso, porque si simplemente estás escogiendo los 11 que tengan la puntuación más alta la lógica de negocio no sería suficiente.

2023-09-26 10:23 UTC, JJ commented on Docs/Historias.md
> +1. Al registrarse el usuario recibe una plantilla de 11 futbolistas aleatoria con valor de 100 Millones y 100 Millones más para fichajes. Lo que genera un presupuesto base de 200 Millones entre los 2
O sea, que el juego ajusta el valor de la plantilla para que sea exactamente 100 millones. Y tienes jugadores que en principio valen 100 millones, y 100 millones en "líquido" para la siguiente jornada. ¿O te lo puedes gastar sobre la marcha?

2023-09-26 10:23 UTC, JJ commented on Docs/Historias.md
> +2. El usuario se encuentra en una "Liga de amigos" con otros contrincantes que tienen equipos distintos.
¿Los jugadores siempre son distintos? ¿Son distintos para todos los usuarios? ¿O sólo dentro de la liga de amigos?

2023-09-26 10:23 UTC, JJ commented on Docs/Historias.md
> +3. Estos futbolistas sumaran puntuaciones en función de su rendimiento en la vida real.
typo. O sea, que cada jornada cambian de puntuación. ¿Cómo se calcula el rendimiento? ¿Hay un sólo número que defina el rendimiento?

2023-09-26 10:23 UTC, JJ commented on Docs/Historias.md
> +4. Cada día el mercado genera nuevos futbolistas para poder comprar según el dinero que se tenga, no se
¿Cada día? ¿No es cada jornada? ¿Esos futbolistas corresponden a futbolistas reales de equipos reales?

2023-09-26 10:23 UTC, JJ commented on Docs/Historias.md
> +haya gastado y no tengan sus contrincantes.
Si lo genera el juego, ¿el primero que lo ve se lo queda?

2023-09-26 10:23 UTC, JJ commented on Docs/Historias.md
> +5. El usuario podrá comprar y vender futbolistas para mejorar su equipo.
¿Cada vez que compra tiene obligatoriamente que vender?

2023-09-26 10:23 UTC, JJ commented on Docs/Historias.md
> +7. Un futbolista solo puede estar en un equipo de la "Liga de amigos" a la vez.
Esto podías aclararlo antes, donde te he hecho la pregunta.

2023-09-26 10:23 UTC, JJ commented on Docs/Historias.md
> +8. El usuario puede realizar la compra de clausulas de otros futbolistas que tengan otros contrincantes
O sea, que hay dos tipos de jugadores: los que estén en otros equipos de tu "liga de amigos" y los que "genere" la liga. ¿Cómo se establece el precio de unos y de otros? ¿y la puntuación de los generados, si es que no han jugado todavía?

2023-09-26 10:23 UTC, JJ commented on Docs/Historias.md
> +9. Cuantos más puntos generen sus futbolistas, más dinero ganará el usuario.
Pero si el precio y el "rendimiento" o "puntos" están relacionados, ¿qué posible optimización hay? Simplemente te compras los más caros que te puedas permitir.
Debe haber alguna otra característica que prediga el rendimiento futuro que se pueda usar para optimizar.

2023-09-26 10:23 UTC, JJ commented on Docs/Historias.md
> +10. El usuario puede tener suplentes, es decir, más de 11 jugadores en su equipo, pero solo 11 podrán puntuar en cada jornada.
O sea, que un problema adicional es seleccionar los jugadores que quieres que jueguen en una jornada determinada. Y una vez más, ¿en función de qué los seleccionas? ¿Qué datos tienes sobre los jugadores que te permitan seleccionarlos?

2023-09-26 11:04 UTC, javigp2002 commented
@JJ He actualizado el user-journey siguiendo sus referencias. No obstante, creo que he comprendido mal este user-journey, yo pretendo enseñar al desarrollador como se juega al _Fantasy_ sin que este deba de conocerlo. Asimismo, nuestra aplicación generará equipos de acuerdo con la puntuación actual y el precio en el mercado que se tenga y, eventualmente, teniendo en cuenta su posición. Estas características son independientes puesto que fluctúan según las semanas y, por tanto, queremos maximizar la puntuación de un equipo de 11 jugadores minimizando el precio de estos.

2023-09-26 12:02 UTC, JJ commented
> @JJ He actualizado el user-journey siguiendo sus referencias. No obstante, creo que he comprendido mal este user-journey, yo pretendo enseñar al desarrollador como se juega al _Fantasy_ sin que este deba de conocerlo. Asimismo, nuestra aplicación generará equipos de acuerdo con la puntuación actual y el precio en el mercado que se tenga y, eventualmente, teniendo en cuenta su posición. Estas características son independientes puesto que fluctúan según las semanas y, por tanto, queremos maximizar la puntuación de un equipo de 11 jugadores minimizando el precio de estos.

Creo que no has entendido bien lo que te digo. En el objetivo 0 comenté que debe haber una lógica de negocio aceptable para que se pueda seguir adelante. Yo entendí que los dos datos con los que estamos trabajando, precio y puntuación, no estaban relacionados. Si están, no hay una lógica de negocio considerable: simplemente maximizar puntuación para el precio que tengas. Comprar el jugador más caro e ir comprando jugadores hasta que te quedes sin dinero. No hay ninguna lógica de negocio (al menos del tipo que se puede testear). Tampoco habría lógica de negocio en seleccionar de todos los jugadores que tienes cuales van a jugar en cada jornada. Los ordenas, y tomas los 11 con más puntuación (por posición o como quieras). Ni en vender jugadores. Vendes el más barato, y compras el más caro que te puedas permitir. Es simplemente búsqueda.

Por eso en el objetivo 0 os comenté que teníais que conocer el problema. Entiendo que tú lo conoces, y que realmente la estrategia que usas no es esa, pero el problema es que en esta descripción no estás incluyendo ningún dato que indique que estás usando algún otro tipo de dato para la estrategia y que, por un lado, sí podría ser aceptable como problema para la asignatura y, por otro lado, permite modelizar el problema realmente.

Por mi expediencia en el tema cuando jugaba a la liga Fantástica Yahoo, había múltiples datos que había que tener en cuenta a la hora de vender o comprar un jugador, cosas como
1. Si iba a jugar fuera o en casa.
2. Por supuesto, si estaba lesionado o se acababa de incorporar de lesión.
3. Si había jugado otra competición antes (como Champions o similar)
4. Todas esas cosas y si había algún otro factor que influyera en que lo iban a alinear o no.
5. La trayectoria en la liga del equipo, si iba en ascenso o descenso.

En resumen, un montón de factores que te permitían decidir si en la siguiente jornada iba a puntuar y por tanto si iba a subir su valor, que imagino que al final es lo que decide alinear y/o quedarte con un jugador o no.

En resumen, me da la impresión de que lo que se trata es de maximizar el valor _futuro_ del equipo, no de maximizar el valor presente, y para maximizar el valor futuro tienes que tener (e incluir en el user journey y en las HUs) más datos, tales como simplemente un enlace o un pantallazo de una página donde se vean todos los factores que influyen en que un jugador escoja para el equipo, trate de comprar o trate de vender un futbolista o no.

Mi consejo es que reflexiones un poco sobre el tema, reformules el problema (que ahora mismo no está formulado como tal, sino como una solución: maximizar la puntuación de los jugadores que uno tiene) y ajustes las historias de usuario al mismo. En realidad no serían grandes cambios, aunque sí tendrías que especificar claramente todos los elementos de decisión que tiene un jugador para hacer cambios o escoger un miembro del equipo en cada jornada.

2023-09-26 12:09 UTC, JJ commented
Es más, ahora que recuerdo en un TFG que dirigí a principio de siglo se tenían en cuenta 3 jornadas pasadas para tomar decisiones. 
[ligayahoo.prn.pdf](https://github.com/javigp2002/LazyFood/files/12727284/ligayahoo.prn.pdf)

(Caray, Dely Valdés y Mendieta, qué tiempos...) En resumen, te repito lo mismo: tienes que tratar de aplicar el conocimiento personal que tienes del juego para incluir todos los factores que influyan en la toma de decisiones, para que en el siguiente objetivo se pueda hacer correctamente un modelo del problema y en el 4 desarrollarse un código que incluya una cierta lógica de negocio.

2023-09-26 15:31 UTC, JJ requested changes
Gracias por haber intentado adaptar mejor lo enviado para poder alcanzar el objetivo; desgraciadamente, no parece que nos vayamos acercando, porque sigo sin ver claro que la heurística que quieres aplicar pueda ser algo con una lógica de negocio que merezca la pena programar y testear. En realidad, al final estás tratando de hacer un algoritmo de predicción, predicción de puntuación futura a partir de actuación pasada. En  [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) del objetivo 0 dice:

> Si requiere un modelo complejo del problema, o un algoritmo complejo para trabajar con ella, puede ser un problema, porque, insisto, lo tiene que programar el estudiante. Si requiere predicción y por tanto un algoritmo de machine learning, doble problema, porque requiere conjunto de entrenamiento y programar el algoritmo. Se pueden usar, sin embargo, modelos ya entrenados siempre que se programe el intérprete de ese modelo.

En este caso requieres un modelo complejo del problema (que tenga prácticamente en cuenta absolutamente todo, hasta el hecho del equipo para el que juegue) y al final predicción, porque de lo que se trata es de ver si el algoritmo _predice_ qué va a suceder en la siguiente jornada.

Debéis entender que en la historia de usuario se codifica el deseo del cliente, que es sagrado en desarrollo ágil. Si lo que quiere es que le sugiera el jugador que va a permitir ganar más puntos, eso es lo que tiene que hacer el programa. Y desgraciadamente, me temo que tal como lo describes el problema no está resuelto *en la realidad* y va a ser imposible que lo resuelvas en la asignatura.

Desgraciadamente, no veo más remedio que sugerirte que investigues otros posibles problemas, relacionados o no con este, y lo más reales posibles, que sí puedan tener solución dentro de esta asignatura.

En ese sentido, lo mejor sería que volvieras a enviar el objetivo 0. Siento las molestias, pero es que por tu descripción inicial entendí que podría aplicarse algo similar al problema de la mochila, no que sería algo parecido a un problema de predicción. Vuelve a enviarlo como si fuera desde 0, pero sigues con el objetivo superado, no lo voy a invalidar.

2023-09-26 15:31 UTC, JJ commented on Docs/Historias.md
> +## HU01: Antonio quiere conocer un equipo con buena previsión para la siguiente jornada con la puntuación óptima y su presupuesto base
Insistes en usar la palabra "conocer". "Conocer" sería si ya existiera y se le revelara de alguna forma. No se trata de eso, y si se tratara, sería solamente buscar. Ya te lo he dicho antes y no comunica con precisión qué es necesario.

2023-09-26 15:31 UTC, JJ commented on Docs/Historias.md
> +Antonio es un jugador de _La Liga Fantasy_ que quiere conocer un equipo para la siguiente jornada con la puntuación óptima de los futbolistas y con su presupuesto base de forma que pueda encontrarlos
Aparte de lo que te digo arriba, y que aquí insistes en lo mismo, esta HU no se corresponde al user journey. No explica el contexto; el jugador tiene ya un equipo, tiene un presupuesto, y necesita, ¿qué exactamente? ¿Sustituir todo el equipo? ¿Comprar un solo jugador sin vender ninguno?

2023-09-26 15:31 UTC, JJ commented on Docs/Historias.md
> +Juan no solo esta preocupado por la compra de jugadores sino también por no perder oportunidades porque coincide con que hay jugadores que son útiles varias jornadas y después desaparecen. Por ello,
`está` lleva acento. Aparte, esto no revela un problema, sino algo que quiere hacer. Las historias de usuario siempre tienen que hablar del resultado, no de qué es lo que tú crees qeu puede ayudar a alcanzar un resultado.

2023-09-26 15:31 UTC, JJ commented on Docs/Milestones.md
> +Modelo con la descripción generada a través de los HUs. Este hito se cumplirá al identificar los datos necesarios sobre los jugadores, asi como, cuando quede un código que lo modularize y contemple l
Por favor, trata de entender qué se pide aquí. "Identificar los datos" tienes que hacerlo tú en las historias de usuario. Lo que hay que hacer es *a partir de* (no *a través de*) crear un modelo del problema.

2023-09-26 15:59 UTC, javigp2002 commented
@JJ Mi descripción inicial iba por el camino de hacer una especie de problema de la mochila, y es lo que pretendía determinar en este objetivo 1 desde el principio pero a mitad, me ha comentado que el sistema carecía de lógica de negocio y por eso lo he cambiado. Quizás no me he expresado con claridad... Pretendía hacer el 11 ideal con el presupuesto base que se adquiere en el fantasy y que simplemente sirva de referencia al usuario para que conozca nuevos jugadores o alternativas para su propio equipo de fantasy, el valor de cada jugador está, las puntuaciones que consigue y según como juega.

Si ve que no es factible pues tendré que volver al 0.

2023-09-26 18:02 UTC, JJ commented
> @JJ Mi descripción inicial iba por el camino de hacer una especie de problema de la mochila, que es lo que describe el objetivo 0, y es lo que pretendía determinar en este objetivo 1 desde el principio pero a mitad, me ha comentado que el sistema carecía de lógica de negocio y por eso lo he cambiado. Quizás no me he expresado con claridad... Pretendía hacer 

El problema de la mochila se puede aplicar si tienes dos cantidades no relacionadas, por ejemplo peso y precio, y fijada una, tienes que maximizar la otra. Por ejemplo, para un peso (o tamaño) determinado, maximizar el valor o el precio. Pero el precio y el valor no tienen nada que ver.

En tu caso, las cantidades están relacionadas. El valor que tiene un jugador es proporcional a su precio. No tienes que aplicar ningún algoritmo recursivo: simplemente ordenando por valor vas a tener el máximo por precio. Al menos eso es lo que yo he entendido de la descripción que haces. Por eso no hay lógica de negocio, sino un algoritmo muy simple.

> el 11 ideal con el presupuesto base que se adquiere en el fantasy y que simplemente sirva de referencia al usuario para que conozca nuevos jugadores o alternativas para su propio equipo de fantasy, el valor de cada jugador está, las puntuaciones que consigue y según como juega.

Y el precio será el mismo que el valor, más o menos. Incluso aunque sean diferentes, simplemente se ordena por valor/precio y y está.

Otro problema sería si tuvieras que comprar exactamente 11 jugadores con un presupuesto. No es el problema de la mochila, pero no podrías gastarte todo el presupuesto en 3 o 4 jugadores excelentes y el resto en los peores.  Pero por lo que comentas en el user journey, el equipo inicial es aleatorio y no es realmente un problema componer un equipo con un presupuesto.

Así que veo dos opciones: o un algoritmo muy simple, que simplemente ordene por valor para seleccionar el equipo que va a jugar de entre todos los jugadores, comprar o vender un jugador, ,o uno muy complejo que trate de predecir valores futuros en función de un modelo complejo del jugador, de la liga, y del equipo. No se me ocurre ninguna posibilidad intermedia que permita sacar adelante un problema para la asignatura en este contexto. 

Quizás un modelo que te diga qué jugadores cambiar, a partir de un algoritmo relativamente simple que calcule el próximo cambio de puntuación a partir de las jornadas anteriores. En el trabajo que te he puesto arriba llegamos a la conclusión que lo más eficiente era optimizar reglas de cambio de jugadores, más que cualquier otra cosa. No lo sé. Piensa a ver si algo en esa línea podría ser suficiente, y reenvía este objetivo, no es necesario que volvamos al anterior.

2023-09-26 18:21 UTC, javigp2002 commented
@JJ Antes había actualizado el objetivo, y lo que quiero expresar es que el rendimiento que están teniendo unos jugadores no es proporcional a su valor. Le pongo un ejemplo, el Girona está ganando todos los partidos con muy buenos partidos y sus jugadores están haciendo de media 10 puntos (lo cual es muchísimo), pero el valor de estos no es superior a los 10M cada uno, sin embargo, Toni Kroos vale 50M y no da mas de 5 puntos. Por tanto, no están relacionados el precio de estos está más marcado por quienes son que por los puntos que realizan, entonces tendríamos que poner un presupuesto límite y encontrar un algoritmo que maximice el rendimiento (puntos) teniendo en cuenta el valor de los mismos.

He cambiado el HU para que un desarrollador vea más claro el problema y sea el usuario el que busca cambiar cada jornada su equipo por uno mejor por el mismo precio.

2023-09-26 18:32 UTC, JJ commented
> @JJ Antes había actualizado el objetivo, y lo que quiero expresar es que el rendimiento que están teniendo unos jugadores no es proporcional a su valor. Le pongo un ejemplo, el Girona está ganando todos los partidos con muy buenos partidos y sus jugadores están haciendo de media 10 puntos (lo cual es muchísimo), pero el valor de estos no es superior a los 10M cada uno, sin embargo, Toni Kroos vale 50M y no da mas de 5 puntos. Por tanto, no están relacionados el precio de estos está más marcado por quienes son que por los puntos que realizan, entonces tendríamos que poner un presupuesto límite y encontrar un algoritmo que maximice el rendimiento (puntos) teniendo en cuenta el valor de los mismos.
> 

Date cuenta que lo que estás mencionando no son los puntos, sino los puntos ganados *en la última jornada*. ¿Es así? ¿El precio del jugador, por otro lado, es fijo? ¿No cambia a lo largo de cada jornada?

> He cambiado el HU para que un desarrollador vea más claro el problema y sea el usuario el que busca cambiar cada jornada su equipo por uno mejor por el mismo precio. Por cierto, gracias por dedicarle tanto tiempo.

Creo que estás mezclando dos problemas diferentes (que serían dos HUs diferentes). "Cambiar" el equipo implica *vender todos los jugadores*  y comprar otros nuevos. ¿Es esa la mejor solución al problema? Problemas diferentes serían

* Comprar todos los jugadores que maximicen la puntuación con el dinero que hay
* Seleccionar algún jugador para vender, porque no está dando rendimiento pero su precio es alto.

A todo esto, también deberías añadir detalles sobre si se puede comprar cualquier jugador o vender cualquiera, o puede suceder que se venda y nadie quiera comprarlo.

En el PR de @pablobarto he mencionado también el establecimiento de la cláusula de rescisión. ¿Puede ser también un problema y se puede cambiar cada jornada? ¿Si te pagan la cláusula de rescisión estás obligado a venderlo?

2023-09-26 23:25 UTC, javigp2002 commented
@JJ  He estado mirando los siguientes objetivos, además de mirar el PR mencionado y, con tus aclaraciones, he intentado darle un nuevo enfoque al problema y crear nuevas HUs.

2023-09-27 05:41 UTC, JJ approved these changes
:+1: 
Creo que has hecho un esfuerzo importante por explicar claramente qué es lo que hay que tratar de resolver. En todo caso, esto tendrá que usarse por otra persona en el objetivo siguiente, y quien se encuentre con una HU tan escueta como las que has escrito tendrá que referirse al user journey o a su propia experiencia, lo cual generará trabajo adicional por tu parte o por la suya.
Te sugeriría por tanto que o bien en el texto o bien cuando transcribas las HUs a issues aquí en GitHub pongas todos los detalles posibles, aclarando por ejemplo qué quieres decir con "rentable", si el que te merece la pena quitarte de en medio porque no sirve para nada (aunque no sé si será así porque puedes tener todos los jugadores que quieras) o si merece la pena venderlo porque vas a sacar mucha pasta (pero perder la puntuación que te den en el futuro).

Ten en cuenta que esta HU01 y la HU02 tienen que terminar en un test que reciba como entrada el equipo actual y como salida un jugador; tendrás que comparar esa salida con el resto de los jugadores y ver que efectivamente es el más rentable.

2023-09-27 05:41 UTC, JJ commented on README.md
> +El usuario, un jugador de La Liga Fantasy, juega con sus amigos todos los años a este juego de móvil. Sin embargo, no está completamente absorbido por el mundo técnico del fútbol y tampoco sigue a lo
A ver como escribes "barsa"...

2023-09-27 05:41 UTC, JJ commented on Docs/Historias.md
> +[Captura Fantasy 1](GerardMoreno.jpeg)
Estos no están incluidos en el PR

2023-09-27 05:41 UTC, JJ commented on Docs/Historias.md
> +6. La venta de jugadores será siempre efectuada por el mercado de la liga de amigos que lo pujará por el valor de este.
Ah, ¿hay pujas?

2023-09-27 05:41 UTC, JJ commented on Docs/Historias.md
> +4. Cada día sale al mercado de la liga de amigos 30 nuevos futbolistas que no pertenecen a ningún equipo de estos y se puja por ellos hasta el final del día. Lo que supone que cada jornada aparecerán
¿Saber qué precio máximo se va a pagar no representa un problema? ¿O simplemente se lo lleva el que más dinero tiene?

2023-09-29 11:28 UTC, merged