[IV-23-24] Objetivo 5
javigp2002/LazyFood pull request #36
Opened 2023-11-18 11:26 UTC by javigp2002

* [ ] ¿Se han establecido criterios previos de elección de la imagen base, así
como los criterios de búsqueda que han conducido a las imágenes que se están
considerando?
* [ ] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la
última versión publicada del lenguage?
* [ ] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
* [ ] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios
irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una
vez, se va a usar cientos o miles de veces)
* [ ] ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [ ] ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
   "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
   comprobado que lo que se instale sea sólo y exclusivamente lo necesario para
   nuestro proyecto?
* [ ] ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [ ] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [ ] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio
en vez del directorio de trabajo?
* [ ] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En
particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué
condiciones *no* deben darse?
* [ ] Si se usan GitHub actions para su publicación, ¿se han considerado
cuidadosamene los criterios (ramas, paths) para que se lancen?
* [ ] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el
directorio que monta, ya que no tiene derecho de escritura?
* [ ] ¿Se ha abierto un shell en el contenedor una vez construida la imagen y
comprobado que los ficheros que se necesitan están todos incluidos, y que no hay
ficheros que no se necesiten?

2023-11-18 14:13 UTC, Morad02 approved these changes
Creo que en general está bastante bien.

2023-11-18 14:13 UTC, Morad02 commented on Docs/eleccion_imagen.md
> +
Con rapidez a qué te refieres?

2023-11-18 14:41 UTC, javigp2002 commented on Docs/eleccion_imagen.md
> +
Ciertamente, no está bien especificado y puede dar lugar a entenderlo erróneamente. Resuelto en [7b32d24](https://github.com/javigp2002/LazyFood/pull/36/commits/7b32d249bd25ec66242e659e220c0e55edc43b5e)

2023-11-18 14:42 UTC, javigp2002 commented
Gracias @Morad02 otra vez por tu revisión 😄. @JJ Listo para revisión.

2023-11-20 12:21 UTC, JJ requested changes
Aparte de lo comentado, de lo que hablamos en clase entendí que ibas a medir también la velocidad; ya puestos podías haberlo hecho y tener un criterio más. Muy bien, por otro lado, usar snyk para examinar los base. Y gracias a @Morad02 por la colaboración, una vez más.

2023-11-20 12:21 UTC, JJ commented on dockerfile
> +COPY deno.json deno.lock ./
¿Qué va a suceder con estos ficheros cuando "montes" el directorio externo? ¿Es necesario que trabajes con ellos en este directorio?

2023-11-20 12:21 UTC, JJ commented on dockerfile
> +LABEL maintainer="javgonper@correo.ugr.esS"
¿Qué otra etiqueta aconsejan las buenas prácticas que se use?

2023-11-20 12:21 UTC, JJ commented on dockerfile
> +RUN chown -R deno:deno /app
¿Por qué necesitas hacer esto?

2023-11-20 12:21 UTC, JJ commented on dockerfile
> +RUN deno cache --lock=deno.lock --reload --lock-write deno.json
Me temo que esto no está lo suficientemente justificado; no hay nada en el issue que diga que tienes que usar esos flags. Sin tener muy claro qué es lo que hace. Si lo que hace es reescribir el `deno.lock` (como parece que dice) no es exactamente lo que se anda buscando.

2023-11-20 12:21 UTC, JJ commented on dockerfile
> +ENTRYPOINT [ "deno", "task", "test", "test/equipo_test.ts" ]
El ENTRYPOINT debería ejecutar *todos* los tests, no sólo el que haya en un momento determinado. Además, `deno task test` no debería tener argumentos.

2023-11-20 17:04 UTC, javigp2002 commented on dockerfile
> +ENTRYPOINT [ "deno", "task", "test", "test/equipo_test.ts" ]
Ciertamente, resuelto en [734ff61](https://github.com/javigp2002/LazyFood/pull/36/commits/734ff6175378f089fe469a9d059c52409683a3c7).

2023-11-20 17:08 UTC, javigp2002 commented on dockerfile
> +RUN chown -R deno:deno /app
Para crear el usuario genérico y poder cambiarlo a este más tarde.

2023-11-20 17:11 UTC, javigp2002 commented on dockerfile
> +LABEL maintainer="javgonper@correo.ugr.esS"
Otra etiqueta que se aconseja cuando son varios autores es _authors_.

2023-11-20 17:12 UTC, JJ commented on dockerfile
> +RUN chown -R deno:deno /app
¿Y eso de qué te sirve? Los permisos que va a tener lo que montes son los del usuario con el que lo hagas, pero sean los que sean, no puedes confiar en que vayas a poder escribir.
Esencialmente, durante la construcción de la imagen no estás haciendo nada en este directorio, y es únicamente durante la construcción cuando vas a necesitarlo

2023-11-20 17:13 UTC, JJ commented on dockerfile
> +LABEL maintainer="javgonper@correo.ugr.esS"
y...

2023-11-20 17:18 UTC, JJ commented on dockerfile
> +COPY deno.json deno.lock ./
¿En qué directorio los estás copiando? ¿Qué va a suceder con el contenido de ese directorio cuando *montes* el externo?

2023-11-20 17:18 UTC, JJ commented on dockerfile
> +COPY deno.json deno.lock ./
Dicho de otro modo, ¿qué `deno.json` y `deno.lock` va a leer?

Si quieres, haz una prueba...

2023-11-20 17:20 UTC, JJ commented
Javi, todos los comentarios son para que consideres hacer algún cambio y tratan de que entiendas mejor qué es lo que estás haciendo. Si no has cambiado nada ni resuelto, no creo que sea todavía el momento de hacer una nueva revisión.

2023-11-23 08:51 UTC, javigp2002 commented on dockerfile
> +RUN chown -R deno:deno /app
No es necesario, el problema es que no estaba en una carpeta que pudiera manejar el usuario genérico. Resuelto en [244bc2a](https://github.com/javigp2002/LazyFood/pull/36/commits/244bc2a2e3f0c34e918d5ff00ced35c94882ac1e)

2023-11-23 08:52 UTC, javigp2002 commented on dockerfile
> +LABEL maintainer="javgonper@correo.ugr.esS"
Efectivamente existe una nueva version de maintainer donde authors está _deprecated_. Además hemos añadido la versión en los metadatos
 Resuelto en [244bc2a](https://github.com/javigp2002/LazyFood/pull/36/commits/244bc2a2e3f0c34e918d5ff00ced35c94882ac1e)

2023-11-23 08:53 UTC, javigp2002 commented on dockerfile
> +COPY deno.json deno.lock ./
Ahora sí lo copio en el home del usuario genérico. Resuelto en [244bc2a](https://github.com/javigp2002/LazyFood/pull/36/commits/244bc2a2e3f0c34e918d5ff00ced35c94882ac1e)

2023-11-23 08:53 UTC, javigp2002 commented
@JJ listo para revisión.

2023-11-23 09:05 UTC, JJ approved these changes
👏

2023-11-23 12:28 UTC, merged