[IV 23-24] Objetivo 2
javigp2002/LazyFood pull request #7
Opened 2023-10-05 08:05 UTC by PabloBarTo

Debatido en el #6 closes #6

2023-10-20 09:02 UTC, javigp2002 commented
Buenas Pablo. He estado mirando los issues y los archivos que has subido. Aunque estás haciendo un buen trabajo los issues no siempre tienen que contestar como se va a resolver el problema. Por otro lado, solo veo 2 clases (Equipo y jugador), aunque no entiendo como se pueden sacar los datos de mi equipo sobre la valoración general del mismo. Según explique en el user journey lo importante reside en como está actuando el jugador en sus equipos reales en las últimas jornadas y para ello está bien que hayas puesto la puntuación por jornada, no obstante, es necesario que se sepa a que equipo **REAL** pertenece el mismo para poder saber también cual va a ser el siguiente oponente. Es decir faltan clases o datos que puedan relacionar mi equipo actual del fantasy, con los jugadores que yo tengo y con sus respectivos equipos. 

¡Mucho ánimo y mencióname para lo que necesites! :fire:

2023-10-20 16:56 UTC, PabloBarTo commented
@javigp2002 he cambiado un poco los archivos intentando adecuarme a lo que me has dicho.

2023-10-21 11:28 UTC, javigp2002 reviewed
@PabloBarTo Buenas, me gusta mucho más la nueva estructura aunque me gustaría que aclararas el tema del puesto del `Equipo Real`. ¡Muy buen trabajo igualmente! Cuando lo hagas lo reviso y ya mencionamos a JJ. 😄

2023-10-21 11:28 UTC, javigp2002 commented on src/equipoReal.ts
> +        this.puesto = puesto;
¿Si esto tiene puesto para que sirve la clasificación? ¿Quizás el #13  se podía haber resuelto con este puesto?

2023-10-21 17:03 UTC, PabloBarTo commented
Tienes razón, voy a cambiarlo a ver que te parece.

2023-10-21 17:15 UTC, PabloBarTo commented
@javigp2002 ya he cambiado lo de la clasificación. Échale un vistazo y me comentas.

2023-10-22 11:42 UTC, javigp2002 commented
@PabloBarTo Ahora si lo veo bastante bien, buen trabajo, comprueba el cuerpo que cumplas todos los tick y pondré después lo mismo.

2023-10-22 18:33 UTC, PabloBarTo commented
@javigp2002 👍

2023-10-23 08:29 UTC, javigp2002 commented
- [x] ¿Los issues que ha planteado la persona son efectivamente problemas y evidencian comprensión de las historias de usuario? Si no es así, es mejor que se le transmita antes de que empiece a crear cualquier código erróneo.

- [x] ¿Has comprobado que efectivamente el compañero/a ha seguido su lista de comprobación?

- [x] ¿El código creado es una modelización válida de las historias de usuario creadas por ti, y te sirve como base para programar la lógica de negocio?

- [x] ¿El código creado sigue las mejores prácticas para el lenguaje de programación que hayáis consensuado, tanto en identificadores, como nombres de ficheros, como disposición de los diferentes ficheros en el repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y aportan código para resolver el problema planteado en el mismo?

- [x] ¿He comprobado que el código compile, o que quien lo ha programado ha lo ha hecho y documentado en el repositorio?

- [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone correspondiente, que será el primero?

- [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en el objetivo 4 para poder programar la lógica de negocio?

2023-10-23 08:45 UTC, JJ requested changes
Buen trabajo, pero a @javigp2002 le pediría que mirara realmente cómo podría usar este código para implementar la lógica de negocio, y si no entiende cómo se llega desde aquí a ese punto, que solicite aclaraciones o lo que sea necesario.

2023-10-23 08:45 UTC, JJ commented on src/calendario.ts
> +class Calendario{
Has desarrollado esto como solución del issue #11. No comentas de qué forma esto es una solución, pero veo al menos que lo que interesa solamente es "el equipo con el que juegue" y "si va mejor o peor en la clasificación". Esto es un array doble que para empezar no incluye el concepto de "siguiente jornada" (ni el concepto de jornada) ni permite acceder fácilmente a cuál es el equipo con el que se va a jugar, ni pasar del nombre del equipo a la clasificación.
En el mensaje de commit pones:

> Al final he creado una clase calendario en la que se guardan todos los partidos de cada jornada

No especificas ni cómo se guardan, ni por qué hay sólo una clase, ni de qué forma la clase está relacionada con la jornada.

Y el mensaje de commit únicamente dice lo que has hecho, no hay ninguna justificación de la solución del problema ni aporta ninguna información adicional que permita entender por qué se ha hecho.

2023-10-23 08:45 UTC, JJ commented on src/equipoReal.ts
> +        this.puesto = puesto;
Y no se ha contestado a esto, ni se ha resuelto.

2023-10-23 08:45 UTC, JJ commented on src/jugador.ts
> +    getEquipoAlQuePertenece(): equipoReal {
Por favor, mirad [en el fichero de los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-2.md#sobre-el-código-definido) cuando es justificable usar getters y cuando no.

2023-10-23 10:20 UTC, PabloBarTo commented on src/equipoReal.ts
> +        this.puesto = puesto;
Lo he resuelto, pero se me olvidó resolver la conversación.

2023-10-23 10:33 UTC, PabloBarTo commented
@JJ ya he modificado lo que me has comentado.

2023-10-23 12:19 UTC, JJ requested changes
"REsolución y explicación xx" no sigue las buenas prácticas, y más cuando *siempre es el mismo mensaje", como se indica en los [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-2.md). El código es siempre solución al issue, no puede ser otra cosa. Y siempre tiene que incluir la explicación. Los primeros 50 caracteres del commit, aparte de referencia el issue, deberían ser el "título" o resumen del commit, como si se estuviera explicando en una transparencia.
Y os recuerdo en todo caso que de lo que se trata en este objetivo es de hacer un modelo del problema, que incluya buscar las estructuras de datos más adecuadas para el mismo.

2023-10-23 12:19 UTC, JJ commented on src/calendario.ts
> +class Calendario{
Este comentario sigue aquí.

2023-10-23 12:19 UTC, JJ commented on src/calendario.ts
> +    private _jornada: number;
`number` puede ser 4.5.

Una cosa es que haya que documentar en los mensajes de commit y otra que la única forma de entender cómo hay que trabajar con algo sea mirar el mensaje de commit. Hacer que la interpretación de una estructura de datos dependa de otra variable diferente es la definición de deuda técnica. ¿Seguro que no hay otra forma de representar la jornada para que:

> saber contra que equipo juega la siguiente jornada para saber si interesa vender a algún jugador o no dependiendo de si el equipo contra el que juega va mejor o peor en la clasificación.

¿Seguro que hay que representar un calendario con un número que se diga por qué jornada se va?¿NO hay estructuras de datos donde se pueda almacenar esa información un poco mejor? ¿A @javigp2002 le parece que con esto se puede poner a trabajar directamente en la lógica de negocio?

2023-10-23 13:53 UTC, javigp2002 commented
@PabloBarTo Es cierto que el calendario como apunta @JJ quizás no ayude mucho a la lógica de negocio y pueda presentar problemas a la hora de la implementación. Si quieres, intenta buscar otra manera de manejar este problema y me comentas para que intentemos llegar los 2 a una mejor solución la cual cumpla mejor los requisitos.

2023-10-24 15:26 UTC, PabloBarTo commented
@javigp2002 He cambiado la forma en la que se puede saber contra que equipo juega el jugador sin la necesidad del calendario.      A ver que te parece.

2023-10-24 19:15 UTC, javigp2002 commented
@PabloBarTo Lo veo bien, que puedas sacar el siguiente rival directamente desde el equipo pero hay que darle una vuelta acerca de como conseguir este rival, no por nada, sino porque el calendario con las jornadas ya está establecido y se sabe quien juega contra quién. De esta manera no tengo claro de donde sacar esta información o si pretendes que sea de fuera. Igualmente, como esto es un problema de estructura si quieres abre un issue o sigue con el calendario.

2023-10-25 08:55 UTC, PabloBarTo commented
@javigp2002 He cambiado de nuevo la estructura, volviendo a añadir el calendario. Revísalo y a ver como lo ves ahora.

2023-10-25 16:21 UTC, javigp2002 reviewed
Yo buscaría otra manera de realizar esta estructura, aunque creo que nos estamos acercando, le daría otra vuelta ya que esta no me convence del todo... Avísame para lo que necesites 😄

2023-10-25 19:00 UTC, PabloBarTo commented
@javigp2002 He hecho unos nuevos cambios. Espero que estos te gusten más.

2023-10-26 07:05 UTC, javigp2002 approved these changes
Ahora si veo mejor los cambios y el nuevo "calendario" no hace que exista tanta dependencia entre las clases. Aunque en el #11 lo dejaría cambiado en un nuevo comentario.

2023-10-26 07:31 UTC, PabloBarTo commented
@JJ Listo de nuevo para revisión.

2023-10-26 11:04 UTC, JJ requested changes
No se pueden usar nunca en un repositorio nombres que lleven mayúsculas, lo dije en clase. Consultad las buenas prácticas de TypeScript para como nombrar un fichero que contenga sólo una clase.

2023-10-26 16:22 UTC, PabloBarTo commented
@JJ ya he modificado eso. Listo de nuevo para revisión.

2023-10-27 07:00 UTC, JJ approved these changes
No hay ninguno de los comentarios que bloquee la aprobación, pero sí es conveniente que los tengas en cuenta antes de que @javigp2002 fusione.

2023-10-27 07:00 UTC, JJ commented on src/equipo_real.ts
> +    getNombre():string{
Los getters y setters no forman parte del modelo, y sólo se deben incluir si explícitamente se solicita en algún issue o historia de usuario.

2023-10-27 07:00 UTC, JJ commented on src/jugador.ts
> +    private equipo_al_que_pertenece: equipoReal;
Este no sigue la misma convención. Aparte, no se suele usar CamelCase para nombres de variables en TypeScript

2023-10-27 12:24 UTC, merged