[IV-23-24] Objetivo 9
javigp2002/LazyFood pull request #84
Opened 2024-01-07 23:54 UTC by javigp2002

✨ Objetivo 9 y fin de IV incoming ✨

2024-01-09 12:49 UTC, danieeeld2 reviewed
No lo he mirado tampoco con mucha profundidad, porque estoy liado con los exámenes, pero parece que esta bastante correcto. Le he prestado más atención a la parte de la API y parece que está correcta. Además, se ve claramente que endpoint aplica la lógica de negocio. Como comentario, para la parte de los tests, para que fueran más legibles, podría ser buena idea que leyera los datos que usas para testar de un fichero a parte, en vez de declararlos todos ahí como constantes :+1: :tada:

2024-01-09 12:52 UTC, javigp2002 commented
Gracias por tu comentario, sí sería más óptimo y legible como hacia en los primeros tests, pero en este periodo que nos encontramos el tiempo para optimizar estas cosillas escasea aunque sería ideal. Muchas gracias @danieeeld2 por tu revisión, @JJ listo para revisión.

2024-01-09 13:47 UTC, JJ requested changes
Me temo que va a hacer falta otra vuelta, sobre todo para que trates de aplicar mejor las convenciones de los APIs REST... Si tienes tiempo de hacerle los cambios que ha comentado @danieeeld2 , mejor.

2024-01-09 13:47 UTC, JJ commented on api/api_controller.ts
> +    async deleteEquipo(nombreEquipo: string) {
¿Qué historia de usuario pide borrar un equipo?

2024-01-09 13:47 UTC, JJ commented on model/bd.ts
> +            return {ok: false};
Primero, usar `POST` para poner toda la información del jugador es cuestionable. ¿Por qué no usas PUT? Segundo, tienes que usar siempre status de HTTP, no mensajes a caso hecho.

2024-01-09 13:47 UTC, JJ commented on model/bd.ts
> +     async postEquipo(body: any){
Igual que arriba. Si ya sabes toda la información del equipo, conviene que uses `PUT`. Se usa `PUT` si se conoce el URI, POST si no. 
En tu caso, el URI podía ser el nombre, que es único, ¿no?

2024-01-09 13:47 UTC, JJ commented on model/bd.ts
> +        for (const key in body) {
Uf, usando el body para cosas que deberían estar en el URI, y usando PUT para modificar parcialmente un URI... No lo acabo de ver. El verbo que se debería usar para esto es `PATCH`. En todo caso, `PUT` es idempotente, así que no puedes devolver el mensaje de arriba si ya existe.

2024-01-11 01:21 UTC, javigp2002 commented on api/api_controller.ts
> +    async deleteEquipo(nombreEquipo: string) {
Cierto, Resuelto en [2383612](https://github.com/javigp2002/LazyFood/pull/84/commits/23836120b56c54b73ebf2e33b20ba8e0fa4ef9cc)

2024-01-11 01:22 UTC, javigp2002 commented on model/bd.ts
> +            return {ok: false};
He resuelto estos dos comentarios en [238ac08](https://github.com/javigp2002/LazyFood/pull/84/commits/238ac08d7ead6a396c5a2987ee8cc6654ffae77c), [587c8f4](https://github.com/javigp2002/LazyFood/pull/84/commits/587c8f42842867a96625f05465e8b6fbcca714ee) y [8f6b96f](https://github.com/javigp2002/LazyFood/pull/84/commits/8f6b96f3355d6c05ab24366e3a377c13c2efeabf). Cierto es que debía devolver el status pero no veo que se haga desde la DB, como he creado un API controller será este el que la maneje y devuelva estos datos al API.

2024-01-11 01:23 UTC, javigp2002 commented on model/bd.ts
> +     async postEquipo(body: any){
Resuelto en https://github.com/javigp2002/LazyFood/pull/84#discussion_r1448176613

2024-01-11 01:23 UTC, javigp2002 commented on model/bd.ts
> +        for (const key in body) {
Es que estaban mal puestos los nombres de las variables, pero sí, los nombres son únicos. [238ac08](https://github.com/javigp2002/LazyFood/pull/84/commits/238ac08d7ead6a396c5a2987ee8cc6654ffae77c)

2024-01-11 01:25 UTC, javigp2002 commented
@JJ  Listo para revisión! Esta siendo dura la cuesta de enero... También he intentado resolver lo que me comentaba Daniel

2024-01-11 09:05 UTC, JJ requested changes
Has currado un montón en esto, y se nota. El único problema grave es el `listen` y el meter datos fijos en un módulo de desarrollo (en vez de ponerlos en test), pero hay otra serie de pequeñas cuestions, desde temas de *naming*, organización de los directorios, los dos APIs que tienes (con la BD y con el API REST), uso de mocks donde parece que no hacen falta... 
En fin, sé que la cuesta es dura, pero no me cabe duda de que le darás una vuelta y saldrá bien, todavía tienes una semanita (casi)

2024-01-11 09:05 UTC, JJ commented on model/bd.ts
> +            return {ok: false};
Si devuelve los datos al API, debe también devolverlos en un formato razonable. Tienes que ver qué es lo que necesita esta función: que cuando termine, el jugador esté creado. Si está creado *al principio*, lo más razonable es simplemente que retorne sin hacer nada, ¿no te parece? Si no, ¿qué va a hacer con esta información quien la reciba?

2024-01-11 09:05 UTC, JJ commented on model/bd.ts
> +            return {ok: false};
Igual que arriba. No puedes crear mensajes de error específicos como valor de retorno de una función. Si realmente piensas que es un error, lanza una excepción. En este caso, como en el anterior, sinceramente no creo que lo sea. Si ya está creado, que vuelva y listo. Pero es que ni siquiera: la operación de introducir en Kv no es "pesada", así que si hay que repetir la operación debería devolver el mismo resultado.

2024-01-11 13:01 UTC, javigp2002 commented on api/api.ts
> +app.listen({ port: 8000 });
Cierto, no hacía falta [dc06a43](https://github.com/javigp2002/LazyFood/pull/84/commits/dc06a43c435a185d4bc0300ce2596fa17eed3ef8)

2024-01-11 13:01 UTC, javigp2002 commented on test/api_test.ts
> +import { app } from "../api/api.ts";
[dc06a43](https://github.com/javigp2002/LazyFood/pull/84/commits/dc06a43c435a185d4bc0300ce2596fa17eed3ef8)

2024-01-11 13:01 UTC, javigp2002 commented on test/api_controller_test.ts
> +import { Jugador } from "../src/jugador.ts";
Vale, gracias. Resuelto en [387c3c5](https://github.com/javigp2002/LazyFood/pull/84/commits/387c3c552512d176fbf51304d48746e7cc29dd62), [b2cb19c](https://github.com/javigp2002/LazyFood/pull/84/commits/b2cb19cfba79c1652b4b66b6a425a7be755cf5b0)

2024-01-11 13:03 UTC, javigp2002 commented on test/api_controller_test.ts
> +        const mockedJugador = mockito.mock(Jugador);
LA verdad que solo he hecho un mock para probar como funcionan y porque me parecen muy útiles a la hora de hacer test unitarios. Con esto, según me informé, consigo que solo se testee la parte del código que necesito en ese momento puesto que los atributos o, el propio jugador en este caso, no afectan al test en sí. 

Es decir, me parecía más intuitivo y quería probarlos y, debido a que no era parte fundamental del objetivo, quería emplearlos de alguna manera. Pero sí, podría utilizar un `Jugador`

2024-01-11 13:05 UTC, javigp2002 commented on test/api_controller_test.ts
> +        const result = await underTest.getOptimo("   ");
Este, como he explicado antes, es simplemente por probar como funcionaban el mock 😄

2024-01-11 13:06 UTC, javigp2002 commented on model/bd.ts
> +const barcelona = new EquipoReal("Barcelona", 3);
Claramente no 👇 , [c8c8596](https://github.com/javigp2002/LazyFood/pull/84/commits/c8c859614d1437421b30855527701ac598438262)

2024-01-11 13:09 UTC, javigp2002 commented
@jj Listo para la ¿última? revisión 😄. He cambiado los problemas graves para pasar el objetivo y le he explicado el porque de los demás debido a que veo este último objetivo como una oportunidad para poder utilizar nuevas formas para los test unitarios.

2024-01-11 13:10 UTC, javigp2002 commented on model/bd.ts
> +const date: Date = new Date("2021-01-01");
No la verdad, 💩 [c8c8596](https://github.com/javigp2002/LazyFood/pull/84/commits/c8c859614d1437421b30855527701ac598438262)

2024-01-11 13:14 UTC, JJ commented on model/bd.ts
> +            return {ok: false};
Si *realmente* quieres devolver algo en caso de que ya esté creado (que ya te digo que es innecesario) la forma correcta sería, primero, que especifiques un tipo de vuelta con unos estados bien definidos o segundo que simplemente devuelvas un Boolean.
En todo caso, con un nombre como `create` no se espera que se devuelva nada, y tal como está definida la función quien la use no espera que se devuelva nada, así que lo más probable (y realmente posible por como está definida) es que lo que se devuelva simplemente se ignore. Que, una vez más, tiene sentido, porque si la intención era crear, ya está creado...

En todo caso, me gustaría que lo reconsideraras. Por el SRP, la responsabilidad de esta función es crear, no crear-comprobando-previamente-si-está-creado. Eso son *dos* responsabilidades, que deberían ir en *dos* funciones diferentes.

2024-01-11 13:16 UTC, javigp2002 commented on model/bd.ts
> +            return {ok: false};
Ah vale ahora si entiendo lo que me comenta. Me pongo con ello

2024-01-11 13:21 UTC, JJ requested changes
Lo siento, pero siendo este el último objetivo me resisto a darlo por aprobado si tienes ciertos antipatrones en el código. Tienes todavía unos días para modificarlo, no creo que te cueste trabajo. Si no estás de acuerdo con lo que digo, podemos hablarlo

2024-01-11 13:21 UTC, JJ commented on model/bd.ts
> +        if (date == undefined) date = new Date();
Vamos a ver, Javi, no hagas trampas en el solitario. ¿Qué pasa si quieres obtener el jugador óptimo de hace tres jornadas, porque se te pasó hacerlo?
Igual esto corresponde correctamente a la historia de usuario, pero si es así, una vez más, la denominación es importante: `getJugadores` primero transmite que quieres recuperar algo que ya existe, y segundo no da la idea de que vas a optimizar los jugadores para la fecha actual.

2024-01-11 13:26 UTC, javigp2002 commented on model/bd.ts
> +        if (date == undefined) date = new Date();
Pero con la HU y el la propuesta no tiene sentido que busques el jugador óptimo de hace 3 semanas, además porque habría que almacenar en la base de datos información de la que ya carecemos. Por tanto, lo que no está claro es el nombre de la función que da lugar a error.

2024-01-11 13:31 UTC, javigp2002 commented on model/bd.ts
> +        if (date == undefined) date = new Date();
Debido a que para los tests, tengo que crear un calendario fictició. Aunque, viendolo así, puedo crear ese calendario con día de hoy también 💯

2024-01-12 11:56 UTC, javigp2002 commented on model/bd.ts
> +            return {ok: false};
Resuelto en [3175851](https://github.com/javigp2002/LazyFood/pull/84/commits/317585162096d2ab8dcbabbbae4d28fc9442b971)

2024-01-12 11:57 UTC, javigp2002 commented on model/bd.ts
> +        if (date == undefined) date = new Date();
Efectivamente hubo un problema al principio cunado se estableció el `Calendario` puesto que se podia introducir una fecha para conocer el óptimo pero eso no es óptimo 😄. Resuelto en:;  [6dd5895](https://github.com/javigp2002/LazyFood/pull/84/commits/6dd589550b2fb234075848d41dad66de5d1861c5), [1388bff](https://github.com/javigp2002/LazyFood/pull/84/commits/1388bff56ac16472fcc32ad4fdb79e89dd274582)

2024-01-12 11:57 UTC, javigp2002 commented
@JJ Listo para revisión 🚀

2024-01-12 12:34 UTC, JJ requested changes
Lo siento, Javi; has corregido muchas cosas, pero el tema de los códigos de estado, que es importante para diseñar adecuadamente un API, no parece que siga las convenciones de REST. Por su importancia [he añadido un item al respecto al fichero de errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-9.md).
Siento entretenerte más con esto, pero ya te falta muy poquito. Ánimo.

2024-01-12 12:34 UTC, JJ commented on src/api_controller.ts
> +        const res = await this.db.getOptimo(nombreEquipo);
Sigues el mismo patrón const x, return x. ¿Crees que la creación de esa variable es necesaria?

2024-01-12 13:18 UTC, javigp2002 commented on src/api_controller.ts
> +        return is_created ? 200 : 400;
Resuelto en [38833b2](https://github.com/javigp2002/LazyFood/pull/84/commits/38833b2d740ad9d7026e73654015688cf29409df)

2024-01-12 13:18 UTC, javigp2002 commented on src/api_controller.ts
> +        const res = await this.db.getOptimo(nombreEquipo);
Cierto, es que antes hacía más cosas y se habrá quedado...  [c948287](https://github.com/javigp2002/LazyFood/pull/84/commits/c94828775bfcc0f04ec7b3fb95cef56817197d39)

2024-01-12 13:18 UTC, javigp2002 commented
@JJ gracias por su tiempo, lo primero. No se disculpe las cosas o están bien o no se aprueba de toda la vida. Listo para revision!

2024-01-12 13:20 UTC, JJ approved these changes
:clap:

2024-01-12 16:19 UTC, merged